/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO = 6;
  /** RegularExpression Id. */
  int RETURN = 7;
  /** RegularExpression Id. */
  int VERDAD = 8;
  /** RegularExpression Id. */
  int FALSO = 9;
  /** RegularExpression Id. */
  int APOSTRO = 10;
  /** RegularExpression Id. */
  int EQ = 11;
  /** RegularExpression Id. */
  int DIF = 12;
  /** RegularExpression Id. */
  int MAYIG = 13;
  /** RegularExpression Id. */
  int MENIG = 14;
  /** RegularExpression Id. */
  int MAY = 15;
  /** RegularExpression Id. */
  int MEN = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int CAR = 18;
  /** RegularExpression Id. */
  int BOOL = 19;
  /** RegularExpression Id. */
  int FLOTANTE = 20;
  /** RegularExpression Id. */
  int FUNCTION = 21;
  /** RegularExpression Id. */
  int ENCABEZADO = 22;
  /** RegularExpression Id. */
  int BREAK = 23;
  /** RegularExpression Id. */
  int DEFA = 24;
  /** RegularExpression Id. */
  int SUMA = 25;
  /** RegularExpression Id. */
  int RESTA = 26;
  /** RegularExpression Id. */
  int MULT = 27;
  /** RegularExpression Id. */
  int DIVISION = 28;
  /** RegularExpression Id. */
  int IGUALDAD = 29;
  /** RegularExpression Id. */
  int DO = 30;
  /** RegularExpression Id. */
  int FOR = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int ELSE = 33;
  /** RegularExpression Id. */
  int SWITCH = 34;
  /** RegularExpression Id. */
  int CASE = 35;
  /** RegularExpression Id. */
  int PAR1 = 36;
  /** RegularExpression Id. */
  int PAR2 = 37;
  /** RegularExpression Id. */
  int LLA1 = 38;
  /** RegularExpression Id. */
  int LLA2 = 39;
  /** RegularExpression Id. */
  int WHILE = 40;
  /** RegularExpression Id. */
  int DOSPUNTOS = 41;
  /** RegularExpression Id. */
  int PUNTOCOMA = 42;
  /** RegularExpression Id. */
  int CARACTER = 43;
  /** RegularExpression Id. */
  int FLOT = 44;
  /** RegularExpression Id. */
  int NUM = 45;
  /** RegularExpression Id. */
  int CAD = 46;
  /** RegularExpression Id. */
  int MM = 47;
  /** RegularExpression Id. */
  int INC = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"b \\u00c2\\u00af& \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "<COMENTARIO>",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"\\\'\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"int\"",
    "\"char\"",
    "\"boolean\"",
    "\"float\"",
    "\"function\"",
    "<ENCABEZADO>",
    "\"break\"",
    "\"default\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"do\"",
    "\"for\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"while\"",
    "\":\"",
    "\";\"",
    "<CARACTER>",
    "<FLOT>",
    "<NUM>",
    "<CAD>",
    "\"++\"",
    "<INC>",
    "\"1\"",
  };

}
